"""Adicionar itens no pedido

Revision ID: fb3f9e0e0898
Revises: 92cb3e6175d0
Create Date: 2026-05-17 17:28:57.849194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb3f9e0e0898'
down_revision: Union[str, Sequence[str], None] = '92cb3e6175d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
